### ISSUE TITLE
A Request "How to output number with thousand separator (Comma Ex.50000=50,000 )"

### ISSUE THREAD

**Issue by ghost** [DanielDrabik/Contact-Form-7-Range-Slider-Extender#2]
Hi! Thanks for such an amazing helpful plugin. Could you please tell me how can I output numbers with php  thousand separator.

Regards

**Comment by DanielDrabik** [comment]
Edit cf7-range-slider-extender.php on line 103:

`$html = sprintf(
		'<span class="wpcf7-form-control-wrap %1$s"><input id="%5$s" oninput="output%5$s.value=%5$s.value" %2$s />%3$s</span><output class="contactform7-output" name="%1$s" id="output%5$s" for="%5$s">%4$s</output>',
		sanitize_html_class( $tag->name ), $atts, $validation_error, $value,  sanitize_tag_name( $tag->name ));`

Change to:

`$html = sprintf(
		'<span class="wpcf7-form-control-wrap %1$s"><input id="%5$s" oninput="output%5$s.value=(+%5$s.value).toLocaleString(\'en-IN\')" %2$s />%3$s</span><output class="contactform7-output" name="%1$s" id="output%5$s" for="%5$s">%4$s</output>',
		sanitize_html_class( $tag->name ), $atts, $validation_error, $value,  sanitize_tag_name( $tag->name ));`

It should be working now.

**Comment by ghost** [comment]
It worked! Thank you ! 
If I had something like that:

$html = sprintf(
				'<span class="wpcf7-form-control-wrap %1$s">%5$s<input style="display:none;" %2$s %4$s />%3$s</span>',
				sanitize_html_class( $tag->name ), $atts, $validation_error, 'data-formulas="'.$value.'"',$custom );

Where %5$s is the output. What I would do?

**Comment by webprojekty** [comment]
Thank you, my code for czech republic is:

`$html = sprintf( '<span class="wpcf7-form-control-wrap %1$s"><input id="%5$s" oninput="output%5$s.value=(+%5$s.value).toLocaleString(\'cs\')" %2$s />%3$s</span><output class="contactform7-output" name="%1$s" id="output%5$s" for="%5$s">%4$s</output>', sanitize_html_class( $tag->name ), $atts, $validation_error, $value, sanitize_tag_name( $tag->name ));`

how can i add after number Kč (CZK) ? like as 100 000 Kč

**Comment by d3rk1ns** [comment]
how can i add a $ simbol on the output value?

**Comment by DanielDrabik** [comment]
@d3rk1ns 
You can do that with CSS
https://github.com/DanielDrabik/Contact-Form-7-Range-Slider-Extender/issues/1#issuecomment-342121200

Or

Line 104:
`'<span class="wpcf7-form-control-wrap %1$s"><input id="%5$s" oninput="output%5$s.value=%5$s.value" %2$s />%3$s</span><output class="contactform7-output" name="%1$s" id="output%5$s" for="%5$s">%4$s</output>',`

Change this:
`oninput="output%5$s.value=%5$s.value"`
Into:
`oninput="output%5$s.value=(%5$s.value + ' $')"`

**Comment by d3rk1ns** [comment]
generate a error. Parse error: syntax error, unexpected '$' in /home/qaserver/public_html/EyeNew/wp-content/plugins/Contact-Form-7-Range-Slider-Extender-master/cf7-range-slider-extender.php on line 107

**Comment by DanielDrabik** [comment]
My bad. I wasn't testing it.

`oninput="output%5$s.value=(%5$s.value + \' $\')"` 

I guess it should work now. Sorry :X
